[versions]
androidx-test = "1.7.0"
androidx-junit = "1.2.1"
appcompat = "1.7.1" # https://developer.android.com/jetpack/androidx/releases/appcompat
biometric = "1.1.0"
core-ktx = "1.17.0"
espresso = "3.6.1" # https://developer.android.com/jetpack/androidx/releases/test
mockito = "5.18.0"
mockito-kotlin = "6.1.0"
androidx-test-orchestrator = "1.6.1"
junit = "5.13.4"
kotlinxCoroutines = "1.10.2"
ktlint-cli = "0.49.1"

[libraries]

androidx-biometric = { group = "androidx.biometric", name = "biometric", version.ref = "biometric" }
androidx-test = { group = "androidx.test", name = "core", version.ref = "androidx-test" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidx-test" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-android = { group = "org.mockito", name = "mockito-android", version.ref = "mockito" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito-kotlin" }
androidx-test-orchestrator = { group = "androidx.test", name = "orchestrator", version.ref = "androidx-test-orchestrator" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }

#Unit test
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }

[bundles]
test = [ "junit-jupiter", "junit-jupiter-params", "junit-jupiter-engine"]

[plugins]
